#docker-compose.prod.yml
version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn resumai.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: resumai.settings.prod
    env_file:
      - .env.prod
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
#    expose:
#      - #작성
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
#    build: #작성
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
#    ports:
#      - #작성
    depends_on:
      - web

volumes:
  static:
  media: