# Generated by Django 5.0.3 on 2024-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="is_finished",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memo",
            name="is_scrapped",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
