# Generated by Django 5.0.3 on 2024-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="available_chat_count",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_chat_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
