# Generated by Django 5.0.3 on 2024-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="position",
            field=models.CharField(default="ML Engineer", max_length=255),
            preserve_default=False,
        ),
    ]
