# Generated by Django 5.0.3 on 2024-04-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resume_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="question",
            field=models.TextField(default="테스트질문"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resume.resume"
                    ),
                ),
            ],
        ),
    ]
