# Generated by Django 5.0.3 on 2024-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_alter_resume_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="query",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="response",
            field=models.TextField(null=True),
        ),
    ]
